name: Build Docker Image
run-name: 👷 Build Docker Image $${{ github.repository }}
on:
    push:
    pull_request:
jobs:
    pre_job:
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip}}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5      
    Build:
                runs-on: ubuntu-22.04
                steps:
                  - uses: actions/checkout@v4
                  - uses: docker/setup-buildx-action@v3
                  - uses: docker/metadata-action@v5
                    id: meta
                    with:
                      images: Build
            
                  - name: Cache
                    uses: actions/cache@v3
                    id: cache
                    with:
                      path: |
                        var-cache-apt
                        var-lib-apt
                      key: cache-${{ hashFiles('.github/workflows/test/Dockerfile') }}
            
                  - name: inject cache into docker
                    uses: reproducible-containers/buildkit-cache-dance@v3.1.0
                    with:
                      cache-map: |
                        {
                          "var-cache-apt": "/var/cache/apt",
                          "var-lib-apt": "/var/lib/apt"
                        }
                      skip-extraction: ${{ steps.cache.outputs.cache-hit }}
            
                  - name: Build and push
                    uses: docker/build-push-action@v5
                    with:
                      context: .
                      cache-from: type=gha
                      cache-to: type=gha,mode=max
                      file: Dockerfile
                      push: ${{ github.event_name != 'pull_request' }}
                      tags: ${{ steps.meta.outputs.tags }}
                      labels: ${{ steps.meta.outputs.labels }}