name: Build Docker Image
run-name: 👷 Build Docker Image $${{ github.repository }}
on:
    push:
    pull_request:
jobs:
    pre_job:
        runs-on: ubuntu-latest
        outputs:
            should_skip: ${{ steps.skip_check.outputs.should_skip}}
        steps:
            - id: skip_check
              uses: fkirc/skip-duplicate-actions@v5      
    Build_job:
                runs-on: ubuntu-22.04
                steps:
                  - uses: actions/checkout@v4
                  - uses: docker/setup-buildx-action@v3
                  - uses: docker/metadata-action@v5
                    id: meta
                    with:
                      images: Build
                  - name: Cache Docker layers
                    uses: actions/cache@v2
                    with:
                      path: /tmp/.buildx-cache
                      key: ${{ runner.os }}-buildx-${{ github.sha }}
                      restore-keys: |
                         ${{ runner.os }}-buildx-
                
                  - name: Build
                    uses: docker/build-push-action@v2
                    with:
                          push: false
                          tags: ${{ steps.prepare.outputs.image }}
                          platforms: ${{ env.DOCKER_PLATFORMS }}
                          cache-from: type=local,src=/tmp/.buildx-cache
                          cache-to: type=local,dest=/tmp/.buildx-cache-new
                          context: .
                
                  - name: Move cache
                    run:
                      rm -rf /tmp/.buildx-cache
                      mv /tmp/.buildx-cache-new /tmp/.buildx-cache