name: Publish Release
run-name: 📦 Create Release $${{ github.repository }}
on:
    push:
        tags:
            - 'v*'
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            packages: write
        steps:
            - uses: actions/checkout@v4
            - name: Create a Release
              #uses: elgohr/Github-Release-Action@v5
              uses: ncipollo/release-action@v1
              #env: 
              #  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              ##with:
                #title: Automated Release