name: Automated Testing
run-name: 🧪 Run Tests on $${{ github.repository }}
on:
  push:
  pull_request:
jobs:
  pester-test:
    name: Pester Test
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Perform a Pester test from the command-line
          shell: pwsh
          run: Test-Path README.md | Should -Be $true
        - name: Perform a Pester test from the Tests.ps1 file
          shell: pwsh
          run: |
            Invoke-Pester Unit.Tests.ps1 -Passthru
