name: Automated Testing
run-name: 🧪 Run Tests on $${{ github.repository }}
on:
  push:
  pull_request:
jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip}}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
  pester-test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != true
    name: Pester Test
    runs-on: ubuntu-latest
    steps:
        - name: Check out repository code
          uses: actions/checkout@v4
        - name: Perform a Pester test from the command-line
          shell: pwsh
          run: Test-Path README.md | Should -Be $true
        - name: Perform a Pester test from the Tests.ps1 file
          shell: pwsh
          run: |
            Invoke-Pester Unit.Tests.ps1 -Passthru
